pipeline {
    agent any
    tools { nodejs "node16.2.0" }
    stages {
        stage ("install") {
            steps { sh "npm install" }
        }
        stage ("test") {
            steps { sh "npm run" }
        }
        stage ("deploy") {
            steps { sh "hola" }
        }
    }
}
