pipeline {
    agent any
    tools { nodejs "node" }
    stages {
        stage ("install") {
            steps {
                sh "cd App"
                sh "npm install"
            }
        }
        stage ("test") {
            steps { sh ".npm test" }
        }
        stage ("deploy") {
            steps { sh "npm start" }
        }
    }
}
