pipeline {
    agent any
    tools { nodejs "node16.2.0" }
    stages {
        stage("Git") {
            steps {
                git branch: "master", url: "https://github.com/Losajhonny/IA1_Proyecto.git"
            }
        }
        stage ("install") {
            steps { sh "npm install" }
        }
        stage ("test") {
            steps { sh "npm test" }
        }
        stage ("deploy") {
            steps { sh "npm start" }
        }
    }
}
